apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: microservice-k8s
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: elsa888/microservice-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: GATEWAY_URL
              value: '/gateway'
